# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Sophia N. Wassermann
# email: hi@sowasser.com
# description: > # this means to ignore newlines until "baseurl:"
#   Porfolio and blog of Sophia N. Wassermann
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://sowasser.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: sowasser
# github_username:  sowasser

# Build settings
# markdown: kramdown
# theme: minima
# gems:
#   - jekyll-feed
# exclude:
#   - Gemfile
#   - Gemfile.lock


# For jekyll uno
# Site settings
title: Sophia N. Wassermann
description: 'PhD Candidate in Marine Science & Irish Research Council Government of Ireland Postgraduate Scholar. Interested in computational approaches to issues at the intersection of fisheries and climate change. Currently modelling mackerel collective behaviour.'
url: 'https://sowasser.com'
#url: 'http://127.0.0.1:4000/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Sophia N. Wassermann'
  email:  hi@sowasser.com
  twitter_username:  sowasser
  #facebook_username: sowasser
  github_username:  sowasser
  linkedin_username:  sowasser

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

